name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup credentials
        run: |
          echo "$DEPLOY_KEY" > $HOME/deploy_key
          chmod 600 $HOME/deploy_key
          echo "$KNOWN_HOSTS" > $HOME/known_hosts
      - name: install packages
        run: yarn install
      - name: setting git config
        run: |
          git remote set-url origin git@github.com:yukishinonome/next-app-001.git
          git config --global core.sshCommand '/usr/bin/ssh -i "$HOME/deploy_key" -o UserKnownHostsFile="$HOME/known_hosts"'
          git config --global user.email 'yuki.yamakoshi0126@gmail.com' && git config --global user.name 'GitHub Actions'
      - name: build storybook
        run: yarn build-storybook
      - name: run deploy
        run: yarn deploy
