name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: yarn install
      - name: setting git config
        run: git config --global user.email 'yuki.yamakoshi0126@gmail.com' && git config --global user.name 'GitHub Actions'
      - name: build storybook
        run: yarn build-storybook
      - name: run deploy
        run: yarn deploy
